name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Download songs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install songs-dl unidecode tqdm
          python -m pip install -r requirements.txt

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Download songs
        run: python build.py

      - name: Build website
        run: sphinx-build -b html source/ build/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
