name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Download songs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade songs-dl unidecode tqdm
        # FIXME Remove dependencies when added to songs-dl requirements

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Download songs and build website
        run: python build.py

      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
