name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linting:
    name: Linting
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - {program: black, command: black . --check}
          - {program: flake8, command: flake8 .}
          - {program: isort, command: isort . --check}
          - {program: pylint, command: 'pylint **.py --evaluation "0 if fatal else max(0, 10 - error - warning)"'}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Get pip cache dir
      id: pip-cache
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.program }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ matrix.program }}

    - name: Run ${{ matrix.program }}
      run: python -m ${{ matrix.command }}
